config/routes.rb
Memrory::Application.routes.draw do
  
  match 'login' => 'auth#login'
  match 'logout' => 'auth#logout'
  match 'checkbrainmailbox' => 'auth#checkbrainmailbox'
  
  resources :users

  resources :neurons do
    collection do
      get "search"
      get "list"
      get "synapses"
      post "login"
      get "logout"
    end
  end

  match 'neurons/label/:id' => 'neurons#label'
  
  

root :to => "neurons#new"

end

app/models/neuron.rb
class Neuron < ActiveRecord::Base
  has_many :assets, :dependent => :destroy
  accepts_nested_attributes_for :assets, :allow_destroy => true
    
  validates_presence_of :name
  validates_uniqueness_of :name
  
	def self.search(search)
           if search
            find(:all, :conditions => ["name LIKE ? or content LIKE ? or labels LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%"], :order => 'LOWER(name) ASC')
           else
           	   find(:all, :order => 'LOWER(name) ASC')
           end
  end  

  def self.search_label(search)
           if search
            find(:all, :conditions => ["labels LIKE ?", "%#{search}%"], :order => 'LOWER(name) ASC')
           else
           	   find(:all, :order => 'LOWER(name) ASC')
           end
  end 
  
  def self.last_ones
    last = Neuron.order("created_at DESC").limit(4)
  end
  
end

app/controllers/neurons_controller.rb
class NeuronsController < ApplicationController
  # GET /neurons
  # GET /neurons.xml
  def synapses
    @tab = "synapses"
  end
  
  def index
    redirect_to :action => "new"
  end
    
  def list
    @tab = "browse"
    @neurons = Neuron.paginate(:page => params[:page], :per_page => 20).order('id DESC')

    respond_to do |format|
      format.html # list.html.erb
      format.xml  { render :xml => @neurons }
    end
  end

  # GET /neurons/1
  # GET /neurons/1.xml
  def show
    @tab = "browse"
    @neuron = Neuron.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @neuron }
    end
  end

  # GET /neurons/new
  # GET /neurons/new.xml
  def new
    @tab = "new"
    @neuron = Neuron.new
    4.times { @neuron.assets.build }
    
    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @neuron }
    end
  end

  # GET /neurons/1/edit
  def edit
    @neuron = Neuron.find(params[:id])
    4.times { @neuron.assets.build }
  end

  # POST /neurons
  # POST /neurons.xml
  def create
    @neuron = Neuron.new(params[:neuron])

    respond_to do |format|
      if @neuron.save
        format.html { redirect_to(@neuron, :notice => 'Neuron was successfully created.') }
        format.xml  { render :xml => @neuron, :status => :created, :location => @neuron }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @neuron.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /neurons/1
  # PUT /neurons/1.xml
  def update
    @neuron = Neuron.find(params[:id])

    respond_to do |format|
      if @neuron.update_attributes(params[:neuron])
        format.html { redirect_to(@neuron, :notice => 'Neuron was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @neuron.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /neurons/1
  # DELETE /neurons/1.xml
  def destroy
    @neuron = Neuron.find(params[:id])
    @neuron.destroy

    respond_to do |format|
      format.html { redirect_to :action => "list" }
      format.xml  { head :ok }
    end
  end
  
	# Executes a search query on the database (cf. model file for the definition of Neuron.search)
	def search
    @tab = "browse"
    @query=params[:search]
    @neurons = Neuron.paginate(:page => params[:page], :per_page => 20).search(params[:search])
  end
  
  def label
    @tab = "browse"
    @label=params[:id]
    @neurons = Neuron.search_label(params[:id])    
  end
  
end

app/helpers/neurons_helper.rb
module NeuronsHelper
  
  #Use the appropriate icon image
  def file_icon_image(upload,size='48px')
    extension = File.extname(upload.file_name).downcase
    if extension.length > 0
      extension = extension[1,10]
    end
    
    if Asset::ICONS.include?(extension)
      if !(upload.document.content_type =~ /^image.*/).nil?
        image_tag(upload.document.url(:thumb))
      else
        image_tag("file_icons/#{size}/#{extension}.png", :class => "file_icon #{extension}")
      end
    else
      image_tag("file_icons/#{size}/_blank.png")
    end
  end
  
  # Transform the list of labels in a list of links to display neurons with same label
  def display_labels(strLabels)
    unless strLabels.nil?
    labels = ""
    strArray = strLabels.split(",")
    strArray.each { |label|
      label=label.strip
      labels = labels.to_str + link_to(label.to_str, :controller=>"neurons", :action=>"label", :id=>label.to_str) + " "
    }
    labels
    else
      ""
    end
  end
  
end

app/views/neurons/_form.html.erb
<div id="stylized">
<%= form_for @neuron, :html => {:multipart => true} do |f| %>
  <% if @neuron.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@neuron.errors.count, "error") %> prohibited this neuron from being saved:</h2>

      <ul>
      <% @neuron.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
    <label>Name</label> <%= f.text_field :name %>
    </div>

    <div class="field">
    <label>Date</label> <%= f.date_select :date %>
    </div>

    <div class="field">
    <label>Labels <span class="small">separated with ","</span></label> <%= f.text_field :labels %>
    </div>

    <div class="field">
    <label>Content</label> <%= f.text_area :content, :cols => 40, :rows => 15 %>
    </div>
  
  
  <div class="newPaperclipFiles">
        <%= f.fields_for :assets do |asset| %>
           <% if asset.object.new_record? %>
                 <label>Select a document</label><%= asset.file_field :document %>
           <% end %>
       <% end %>
  </div>
  <br />
  <br />
  
  <div class="portfolio">
     <% empty_portfolio=true %>
     <%= f.fields_for :assets do |asset| %>
        
          <% unless asset.object.new_record? %>
        
            <div class="thumbnail">            
              <%= link_to(file_icon_image(asset.object), asset.object.document.url(:original)) %>
              Delete the file? <%= asset.check_box :_destroy %> (yes if checked)
            </div>
          <% empty_portfolio=false %>
          <% end %>        
        
     <% end %>
          
    <% unless empty_portfolio==false %>
        <%= "Empty portfolio"  %>
      <% end %>
  </div>
  <br />
  <br />
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/neurons/_list_table.html.erb
<table class="table-with-style">
  <tr>
    <th>Name</th>
    <th>Date</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @neurons.each do |neuron| %>
  <tr>
    <td><%= link_to neuron.name, neuron %></td>
    <td><%= neuron.date %></td>
    <td><%= link_to image_tag("/images/look.gif"), neuron %></td>
    <td><%= link_to image_tag("/images/edit.gif"), edit_neuron_path(neuron) %></td>
    <td><%= link_to image_tag("/images/delete.gif"), neuron, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<div class="pom_pagination">
<%= will_paginate @neurons %>
</div>

app/views/neurons/edit.html.erb
<h1>Editing neuron</h1>

<%= render 'form' %>

<%= link_to 'Show', @neuron %> |
<%= link_to 'Back', neurons_path %>

app/views/neurons/label.html.erb
<h1>List of neurons with the label ""<%= @label %>""</h1>

<%= render 'list_table' %>

app/views/neurons/list.html.erb
<h1>Listing neurons</h1>

<%= render 'list_table' %>

app/views/neurons/new.html.erb
<h1>Add a neuron to the brain</h1>

<%= render 'form' %>

app/views/neurons/search.html.erb
<h1>Search results for query "<%= @query %>"</h1>

<%= render 'list_table' %>

app/views/neurons/show.html.erb
<h1>Show the neuron <%= @neuron.id %></h1>

<p>
  <b>Name:</b>
  <%= @neuron.name %>
</p>

<p>
  <b>Date:</b>
  <%= @neuron.date %>
</p>

<p>
  <b>Neuron's labels:</b>
  <%= display_labels(@neuron.labels).html_safe %>
</p>

<b>Neuron's content</b>
<div class="neuron">  
    <%= RDiscount.new(@neuron.content).to_html.html_safe %>    
</div>

<b>Neuron's assets</b>
<p class="portfolio">
    <% empty_portfolio=true %>
    <% @neuron.assets.each do |asset| %>    
    <%= link_to( file_icon_image(asset), asset.document.url(:original)) + asset.file_name + " (" + number_to_human_size(asset.file_size) + ")"  %> 
    <br/>
    <% empty_portfolio=false %>
    <% end %>
    <% unless empty_portfolio==false %>
        <%= "Empty portfolio"  %>
    <% end %>
</p>

<%= link_to 'Edit', edit_neuron_path(@neuron) %> |
<%= link_to 'Back', neurons_path %>

app/views/neurons/synapses.html.erb
<div class="post">
<h1>Doc, is it growing ?</h1>
</div>

<div class="post">
  <h3>Hummmm...</h3>
  Any man who reads too much and uses his own brain too little falls into lazy habits of thinking. Albert Einstein.
</div>